### ISSUE TITLE
Error messages during run

### ISSUE THREAD

**Issue by rmarquet** [ziebelje/sqlbee#4]
I sometimes get the following error messages when the program runs.  I only get one set at a time - not all three - but I posted them in one issue report because it may have a similar root cause.

> PHP Notice:  Undefined index: thermostatList in /sqlbee-master/sqlbee.php on line 367
> PHP Warning:  Invalid argument supplied for foreach() in /sqlbee-master/sqlbee.php on line 367

> PHP Notice:  Undefined index: reportList in /sqlbee-master/sqlbee.php on line 486
> PHP Warning:  Invalid argument supplied for foreach() in /sqlbee-master/sqlbee.php on line 486
> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'on duplicate key update `thermostat_id` = values(`thermostat_id`),`timestamp` = ' at line 1

> PHP Notice:  Undefined index: revisionList in /sqlbee-master/sqlbee.php on line 256
> PHP Warning:  Invalid argument supplied for foreach() in /sqlbee-master/sqlbee.php on line 256

I haven't had time to dig into sqlbee to see if I can figure out what's triggering this.  I'm guessing sqlbee isn't always getting the data it's expecting from ecobee, so this happens.  I'm pretty sure it's not a bug in sqlbee because other runs work without errors and load the data just fine.  sqlbee may need to be better at handling unexpected/missing data, though.

**Comment by ziebelje** [comment]
Those errors would be consistent with the ecobee API not returning the expected results (or throwing an error). It's certainly possible that, in my limited testing of one ecobee, I missed some edge cases. :)

In your `configuration.php`, would you set `$log_api_calls = true` and get some logs for me?

I would be interested in seeing the `json_arguments` and `response` columns for those errors. The error on line 367 would be for the `/1/thermostat` endpoint. The error on line 486 would be for the `/1/runtimeReport` endpoint. The error on line 256 would be for the `/1/thermostatSummary` endpoint.

I'm guessing the ecobee API is returning an error or something that I'm not handling. It will probably be pretty obvious when looking at the `response` column for those API calls that something is wrong.

When posting your logs, I would recommend hiding the value for `selectionMatch` from `json_arguments` and `thermostatIdentifier` from `response`. That's just a unique identifier for your ecobee...pretty harmless but better to be safe.

Finally...I'll make a note to add some better error handling so this data is easier to capture for debugging.

**Comment by rmarquet** [comment]
No problem - I've made the change to the config and will report back when it next happens.

**Comment by bob109** [comment]
As another data point to this issue.  I run my cron job every 10 minutes on the 4's.  These errors seem to happen every hour, although sometime they change by 10 minutes.  (ie 6:04, 7:04 8:04 8:54, 9:54...)  
I'll set my config to log the api too.

**Comment by ziebelje** [comment]
Thanks, @bob109. That's actually perfect because now I know what the issue is. It's being caused by the authentication token expiring; they expire after an hour and I then have to send a new request to get another one. I'm obviously just not stopping the script properly. I should be able to fix this pretty easily. I'll tackle this after I finish #2 today or tomorrow.

**Comment by bob109** [comment]
I can confirm the token expiration. Here's your /1/thermostatSummary response
{
  "status": {
    "code": 14,
    "message": "Authentication token has expired. Refresh your tokens. "
  }
}

Here are the other logs.  I noticed the 1/thermostat response was too long to capture all the data.

[1.thermostat_json.arguments.txt](https://github.com/ziebelje/sqlbee/files/636921/1.thermostat_json.arguments.txt)

I don't have a /1/runtimeReport endpoint for the time when I got the error. 

Hope this helps
bob

**Comment by ziebelje** [comment]
Thanks; that confirms it!

Note: I removed your /1/thermostat response text file from your comment as it contains things like your home address, email, etc in addition to the thermostat identifier.

**Comment by ziebelje** [comment]
So, in looking at this I see two issues:

1. The issue that @rmarquet reported exists and is the result of an error returning that is not `code = 14, token expired`. Looking at my API logs I do see the occasional error happening (I got a lot of `code = 3, internal error`) which would trigger the notice in PHP. I am now throwing an exception when these happen instead of allowing script execution to continue. I can't prevent these errors from happening because sometimes the API just throws an error. I could silently kill the script but that feels dishonest and doesn't allow you to log or act on the exception when it happens. This issue will thus be resolved when I push next.

2. The issue that @bob109 reported is actually normal. Every hour you should see that error message in the api_log table if you have logging enabled. The API authentication provides you with a token that works for an hour. When that hour is up you need to request a new token. I do all this, but I don't make any attempt to renew tokens on the hour. Instead, I just wait for a failed API call with a result of `code = 14, token expired`). When I get one I take that as my cue to refresh the token and then re-run the failed API call. I don't believe it was related to the original reported issue.
